variable "azurerm_virtual_network_name" {}
variable "azurerm_subnet_name" {}
variable "azurerm_resource_group" {}
variable "azurerm_location" {}
variable "azurerm_linux_vm_name" {}
variable "azurerm_nic_name" {}
variable "azurerm_vm_count" {}
variable "azurerm_nic_count" {}
variable "azurerm_mssql_database_name" {}
variable "azurerm_mssql_server_name" {}
